[phases.setup]
nixPkgs = ["python3", "pip", "cmake", "gcc", "gcc-unwrapped", "pkg-config", "opencv", "dlib"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "gunicorn web_server:app --bind 0.0.0.0:$PORT"
